blank_issues_enabled: false
contact_links:
  - name: Report UI5 CLI Issues or Request a Feature
    url: https://github.com/UI5/cli/issues/new/choose
    about: Please create new issues in the UI5 CLI repository
