name: GitHub CI

on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4

# No permissions are required for this workflow
permissions: {}

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js LTS 20.11.0
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Perform checks and tests
      run: npm test

    - name: Send report to Coveralls
      uses: coverallsapp/github-action@v2.3.6
