name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        version: [16, 18, 19]
        os: [ubuntu-22.04, windows-2022, macos-13]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run unit-error
